package com.htk.ecommerce.repositories;

import com.htk.ecommerce.models.Category;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ICategoryRepository extends JpaRepository<Category, Long> {

    /*
        Implementation is automatically generated by JPA and Spring Boot,
        generated implementations should always follow findByFieldName naming convention
     */
    Category findByCategoryName(String categoryName);

}
